export const THRESHOLDS = {
  noiseRatioMed: 0.15,
  toolIdleRatioHigh: 0.5,
  toolIdleSavingsHigh: 0.5,
  cacheBreakSavingsHigh: 1,
  cacheBreakReadDropMin: 200,
  cacheBreakWriteJumpMin: 200,
  // PRD FR-AG-4 D2: loss ≈ rewritten cache_creation tokens × 1.25 × input price
  cacheWriteCostMultiplier: 1.25,
  duplicateMinCount: 3,
  duplicateRatioMed: 0.2,
  oversizeTokens: 10_000,
  oversizeMedTokens: 20_000,
  compactableHistoryRatio: 0.3,
  toolFailureMinErrors: 2,
  toolFailureErrorRate: 0.3,
  readChurnMinCalls: 3,
  readChurnRepeatRate: 0.5,
  contextGrowthMinTurns: 4,
  contextGrowthRatio: 1.8,
  modelMismatchMinTokens: 1_000,
};
